import = [
  "~/.config/alacritty/nord.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"

  [window.dimensions]
  columns = 150
  lines = 45

  [window.padding]
  x = 20
  y = 20

[font]
size = 14.0

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono NFM"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono NFM"
  style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true
