[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

[colors.normal]
black = "#4d6b66"
red = "#bf616a"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x5e81ac"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x8FBCBB"
white = "0xECEFF4"
