[[language]]
name = "rust"
auto-format = false

[[language]]
name = "lua"
auto-format = false

[[language]]
name = "bash"
auto-format = false
file-types = [
{ glob= ".aliases" },
{ glob= ".zshrc" },
{ glob= "zshrc" },
{ glob= ".zprofile" },
{ glob= "zshenv" },
{ glob= ".zshenv" },
{ glob= "zprofile" },
{ glob= "conf" },
{ glob= "zsh "}
]
shebangs = ["sh", "bash", "zsh"]

[[language]]
name = "python"
auto-format = false

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "yaml"
auto-format = false

[[language]]
name = "toml"
auto-format = false
