import = [
  "~/.config/alacritty/nord.toml"
]

[env]
TERM = "xterm-256color"
SHELL = "/usr/bin/zsh"

[window]
dynamic_padding = true
decorations = "none"

  [window.dimensions]
  columns = 122
  lines = 45

  [window.padding]
  x = 20
  y = 20

[font]
size = 11.0

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true
