theme = "gruvbox_soft"

[editor]
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
auto-completion = true
true-color = true
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.search]
smart-case = false

[editor.whitespace]
render = 'all'

[editor.whitespace.characters]
space = ' '

[editor.indent-guides]
render = true
