"attribute" = "nord7"
"keyword" = { fg = "nord11" }
"keyword.directive" = "nord11"
"namespace" = "nord7"
"punctuation" = "nord12"
"punctuation.delimiter" = "nord12"
"operator" = "nord15"
"special" = "nord15"
"variable.other.member" = "nord9"
"variable" = "nord5"
"variable.builtin" = "nord12"
"variable.parameter" = "nord5"
"type" = "nord13"
"type.builtin" = "nord13"
"constructor" = { fg = "nord15", modifiers = ["bold"] }
"function" = { fg = "nord14", modifiers = ["italic"] }
"function.macro" = "nord7"
"function.builtin" = "nord13"
"tag" = "nord11"
"comment" = { fg = "nord9", modifiers = ["italic", "dim"] }
"constant" = { fg = "nord15" }
"constant.builtin" = { fg = "nord15", modifiers = ["bold"] }
"string" = "nord14"
"constant.numeric" = "nord15"
"constant.character.escape" = { fg = "nord5", modifiers = ["bold"] }
"label" = "nord7"
"module" = "nord7"

"diff.plus" = "nord14"
"diff.delta" = "nord12"
"diff.minus" = "nord11"

"warning" = "nord12"
"error" = "nord11"
"info" = "nord7"
"hint" = "nord10"

"ui.background" = {}

# Number Lines
"ui.linenr" = { fg = "nord3" }
"ui.linenr.selected" = { fg = "nord13", modifiers = ["bold"] }

# Cursor
"ui.cursor.primary" = { fg = "nord0", bg = "nord4" }
"ui.cursor.match" = { fg = "nord4", bg = "nord3" }
"ui.cursorline.primary" = { bg = "nord1" }
"ui.cursorline.secondary" = { bg = "nord1" }
"ui.cursorcolumn.primary" = { bg = "nord1" }
"ui.cursorcolumn.secondary" = { bg = "nord1" }

# Selections
"ui.selection.primary" = { fg = "nord0", bg = "nord6" }
"ui.selection" = { fg = "nord1", bg = "nord4" }

# Statusline
"ui.statusline" = { fg = "nord4" }
"ui.statusline.inactive" = { fg = "nord3"}
"ui.statusline.normal" = { fg = "nord2", bg = "nord14" }
"ui.statusline.insert" = { fg = "nord13", bg = "nord11" }
"ui.statusline.select" = { fg = "nord1", bg = "nord15" }

"ui.popup" = { bg = "nord1" }
"ui.window" = { bg = "nord0" }
"ui.help" = { bg = "nord1", fg = "nord4" }
"ui.text" = { fg = "nord4" }
"ui.text.focus" = { fg = "nord4" }
"ui.menu" = { fg = "nord4", bg = "nord2" }
"ui.menu.selected" = { fg = "nord2", bg = "nord10", modifiers = ["bold"] }
"ui.virtual.whitespace" = "nord3"
"ui.virtual.ruler" = { bg = "nord3" }

"diagnostic.warning" = { underline = { color = "nord12", style = "curl" } }
"diagnostic.error" = { underline = { color = "nord11", style = "curl" } }
"diagnostic.info" = { underline = { color = "nord7", style = "curl" } }
"diagnostic.hint" = { underline = { color = "nord10", style = "curl" } }

"markup.heading" = "nord7"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "nord14", modifiers = ["underlined"] }
"markup.link.text" = "nord11"
"markup.raw" = "nord11"

[palette]
# Backgrounds
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"

# Foregrounds 
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"

nord7 = "#8fbcbb" # Aqua 1
nord8 = "#88c0d0" # Aqua 2
nord9 = "#81a1c1" # Blue 1
nord10 = "#5e81ac" # Blue 2

nord11 = "#bf616a" # Red
nord12 = "#d08770" # Orange
nord13 = "#ebcb8b" # Yellow
nord14 = "#a3be8c" # Green
nord15 = "#b48ead" # Purple
