theme = "nord_soft"

[editor]
color-modes = true
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
auto-completion = true
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name"]
right = ["diagnostics", "position", "total-line-numbers", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.search]
smart-case = false

[editor.whitespace]
render = 'all'

[editor.whitespace.characters]
space = ' '

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

# Key Remaps
[keys.normal]
C-j = ":hs"
C-k = ":hs"
C-h = ":vs"
C-l = ":vs"

# [editor.soft-wrap]
# enable = true
# max-wrap = 25
# max-indent-retain = 0
# wrap-indicator = ""
