[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[grammar]]
[[language]]
name = "lua"
auto-format = true

[[language]]
name = "bash"
auto-format = true
file-types = [".aliases", ".tmux.conf", ".zshrc"]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "yaml"
auto-format = false

[[language]]
name = "toml"
auto-format = false
# Taplo is disabled due to a known bug in the LSP
language-server = { command = ""}