[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[grammar]]

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "bash"
auto-format = true
file-types = [".aliases", ".tmux.conf"]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false