[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "bash"
auto-format = true
file-types = [".aliases", ".zshrc", "conf", "zsh"]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "html"
auto-format = true

[[language]]
name = "css"
auto-format = true

[[language]]
name = "yaml"
auto-format = true

[[language]]
name = "toml"
auto-format = true
# Taplo is disabled due to a known bug in the LSP
language-server = { command = ""}